baseURL: https://tafadzwac.netlify.app/
languageCode: en-us
title: Tafadzwa Chinanzvavana
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Explore
    subtitle: |-
      Welcome to my website. I am currently an MFA Student at London Business School and I will be sharing my journey and work with you here.
    title: Hi, my name is Tafadzwa Chinanzvavana
  blog: {}
  contact:
    address:
      - city: London, NS1 4SA
        country: United Kingdom
        street: Sussex Place
        title: Sussex Place
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tafadzwac.mfa2022@london.edu
        title: Email
    enable: yes
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://tafadzwac.netlify.app/
    social:
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://au.linkedin.com/in/tafadzwachinanzvavana
  image: ''
  name: Tafadzwa Chinanzvavana
  navigation:
    button1:
      - name: Explore
        url: blogs
    links:
      - name: Home
        url: 
      - name: About Me
        url: blogs/about
      - name: Education
        url: blogs/education
      - name: Work Experience
        url: blogs/work
      - name: Blogs
        url: '# blogs '
    menu: Menu
    title: 
  tiles:
    enable: yes
    showcase:
      - image: pic1.JPG
        subtitle: Who is Tafadzwa
        title: About me
        url: blogs/about
      - image: lbs pic.jpg
        subtitle: My journey to London Business School
        title: Education
        url: blogs/education
      - image: cv.jpg
        subtitle: Career aspirations
        title: Work Experience
        url: blogs/work
      - image: interests.JPG
        subtitle: Fun time!
        title: Interests
        url: blogs/ipsum
      - image: data.jpg
        subtitle: Data Analytics for Finance coursework
        title: R projects
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Explore
    enable: yes
    subtitle: "Please feel free to reach out to me on Linkedin or by using the form below if you have any questions. All enquires will be responded to within 48 hours"
    title: Contact Info
    url: blogs
