baseURL: http://example.org/
languageCode: en-us
title: Portfolio website for Tafadzwa Chinanzvavana
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Explore
    subtitle: |-
      Welcome to my website. I am currently an MFA Student at London Business School and I will be sharing my journey and work with you here.
    title: Hi, my name is Tafadzwa Chinanzvavana
  blog: {}
  contact:
    address:
      - city: London, NS1 4SA
        country: United Kingdom
        street: Sussex Place
        title: Sussex Place
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tafadzwac.mfa2022@london.edu
        title: Email
    enable: yes
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://tafadzwac.netlify.app/
    social:
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://au.linkedin.com/in/tafadzwachinanzvavana
  image: ''
  name: Tafadzwa Chinanzvavana
  navigation:
    button1:
      - name: Explore
        url: blogs
    links:
      - name: Home
        url: '# about'
      - name: About Me
        url: '#about me'
      - name: Education and Work Experience
        url: '# education and work experience'
      - name: Blogs
        url: '# blogs '
    menu: Menu
    subtitle: By HTML5 Up
    title: 
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Explore
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
